version: '3.8'

services:
  db:
    image: postgres:16
    container_name: clothing_store_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: clothing_store
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: clothing_store_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/clothing_store
    depends_on:
      - db

volumes:
  db_data:
